kind: pipeline
name: app-ecs-cfn-ecr-pipeline

steps:
- name: validate cfn tempate
  image: robertstettner/drone-cloudformation
  settings:
    mode: validate
    stackname: app-ecs-cfn-stack
    template: templates/infrastructure.json
    access_key: 
      from_secret: AWS_ACCESS_KEY
    secret_key:
      from_secret: AWS_SECRET_KEY

- name: create cfn stack
  image: robertstettner/drone-cloudformation
  settings:
    pull: true
    stackname: app-ecs-cfn-stack
    template: templates/infrastructure.json
    region: us-east-1
    access_key: 
      from_secret: AWS_ACCESS_KEY
    secret_key:
      from_secret: AWS_SECRET_KEY
    params:
      Version: 1
      Environment: staging
    when:
      event: deployment

- name: deploy docker image to ecs service
  image: omerxx/drone-ecs-plugin
  settings:
    cluster: simple-go-web-app-ecs-cluster
    service: simple-go-webserver-service
    region: us-east-1
    family: simple-go-webserver-task
    image_name: chaturvedisulabh/simple-go-webserver
    image_tag: latest
    access_key: 
      from_secret: AWS_ACCESS_KEY
    secret_key:
      from_secret: AWS_SECRET_KEY
    port_mappings:
      - 80 80
    memory: 256