pipeline:
  validate-template:
    image: robertstettner/drone-cloudformation
    mode: validate
    template: templates/infrastructure.json
    access_key: 
    secret_key:
  deploy:
    image: robertstettner/drone-cloudformation
    stackname: app-ecs-cfn-stack
    template: templates/infrastructure.json
    region: us-east-1
    params:
      Version: 1
      Environment: staging
    access_key: AKIAJPLVJEU6QKDKQU5A
    secret_key: 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
    when:
      event: deployment