jobs:
  - name: Immutable-Infrastructure-IaC-Pipeline
    type: runSh
    steps:
      - IN: app-docker-ecs-gitrepo
        switch: off
      - IN: aws_cliConfig
      - TASK:
          - script: aws cloudformation validate-template --template-body file://${APP_GITREPO_STATE}/infrastructure.json --region us-east-1
          - script: aws cloudformation create-stack --stack-name myteststack  --template-body file://${APP_GITREPO_STATE}/infrastructure.json --region us-east-1
          - script: ${APP_GITREPO_STATE}/docker-task.sh createrepo
          - script: ${APP_GITREPO_STATE}/docker-task.sh build
          - script: ${APP_GITREPO_STATE}/docker-task.sh push
